### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by ghost** [mefengl/vscode-i-dont-care-about-commit-message#21]
<img width="771" alt="image" src="https://github.com/mefengl/vscode-i-dont-care-about-commit-message/assets/106857035/ddc78304-ca65-44b8-b62f-49abc992497e">

<img width="260" alt="image" src="https://github.com/mefengl/vscode-i-dont-care-about-commit-message/assets/106857035/4de77048-5051-4a96-93cd-cdcb7f598ef2">

**Comment by ghost** [comment]
It should be due to limitations imposed by the OpenAI API.

**Comment by mefengl** [comment]
Good point; we do need to handle some common error codes instead of showing them directly to the user.

429 does mean come to the request limit, such as 3 in 1 minute; I found it in: https://platform.openai.com/docs/guides/error-codes/api-errors

I also found more context in the below links:

https://help.openai.com/en/articles/6891839-api-error-code-guidance
https://help.openai.com/en/articles/6897213-openai-library-error-types-guidance
https://callmefred.com/how-to-fix-openai-error-ratelimiterror-the-server-had-an-error

**Comment by mefengl** [comment]
Closed by https://github.com/mefengl/vscode-i-dont-care-about-commit-message/commit/f02394e508bfbff7dbf1b8329e929ec164df9c39
